---
name: Documentation to gh-pages

on:
  schedule:
    # only once every month, at the 23rd
    # We can always force run this.
    - cron: '37 10 23 * *'
  workflow_dispatch:


jobs:
  check_commit:
    runs-on: ubuntu-latest
    name: Checks for latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: false
      - name: Print the latest commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: Check the latest commit is within 1 week
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list --after="1 week" --max-count=1 ${{ github.sha }}) && echo "::set-output name=should_run::false"

  build:
    # check that a commit has actually been made and only run if a commit has been made within the last week
    needs: check_commit
    if: ${{ needs.check_commit.outputs.should_run != 'false' }}
    name: Build documentation

    runs-on: ubuntu-latest

    steps:

      - id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v2

      - name: Install OS packages
        run: sudo apt install -y pandoc

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
        with:
          # The files submodule is required for viz documentation
          submodules: true
          # the files submodule uses lfs
          lfs: true
          fetch-tags: true

      - name: Ensure fortran
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: gcc
          version: 13

      - name: Setup python environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install sisl + documentation dependencies
        env:
          # There is no need for a complete build... Just do it quickly!
          SKBUILD_CMAKE_BUILD_TYPE: Debug
        run: |
          python -m pip install --progress-bar=off --upgrade pip
          python -m pip install --progress-bar=off .[analysis,viz] --group docs
          # So since kaleido does not install chrome, we have to do it
          # This is only necessary when it works, otherwise, skip it!
          kaleido_get_chrome || true

      - name: Build the documentation using the sisl-files as well
        env:
          SISL_NUM_PROCS: ${{ steps.cpu-cores.outputs.count }}
          SISL_NODES_EXPORT_VIS: t
        run: |
          cd docs
          make html
          rm -rf build/html/_sources
          # Ensure it's not understood as a jekyll page
          touch build/html/.nojekyll
          cd ..
          ls -l

      - name: Upload files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          retention-days: 4
          path: docs/build/html/

  deploy:
    needs: build
    name: Deploy to gh-pages

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      # Deploy to github pages
      - name: Deploy to github pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
